language: python

install:
  - "pip install -r requirements.txt"

script:
  - python tests/test_apod.py
  - python tests/test_asterank.py
  - python tests/test_earth.py
  - python tests/test_helioviewer.py
  - python tests/test_maas.py
  # - python tests/test_patents.py
  # - python tests/test_predictthesky.py
  - python tests/test_skymorph.py
  - python tests/test_star.py
  - python tests/test_techport.py
  - python tests/test_temperature_anomalies.py


notifications:
  email: false

branches:
  only:
    - master
